api:
  dashboard: true
  debug: true
log:
  level: INFO
accesslog: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    asDefault: true

serversTransport:
  insecureSkipVerify: true

providers:
  swarm:
    exposedByDefault: false
    network: proxy
  file:
    filename: /config.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: YOUR_CLOUDFLARE_EMAIL
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
